import { Project } from '@/types/projects.types';

export const PROJECTS: Project[] = [
  {
    id: 'project1',
    title: 'Riding Cities',
    category: 'OpenClassrooms',
    description:
      "Le projet 2 du parcours Intégrateur Web d'OpenClassrooms nous permet de découvrir les fondamentaux du langage HTML au travers du site Internet de Riding Cities. Riding Cities est une association fictive de skateboard.",
    competences: [
      'Intégrer des éléments sur une page web en utilisant les fondamentaux de HTML',
    ],
    tags: ['HTML', 'CSS'],
    pictures: [
      '/assets/projects/riding-cities/mock0.webp',
      '/assets/projects/riding-cities/mock1.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Riding-Cities/',
    codeLink: 'https://github.com/Matthieu83600/Riding-Cities',
  },
  {
    id: 'project2',
    title: 'Booki',
    category: 'OpenClassrooms',
    description:
      "Le projet 3 du parcours Intégrateur Web d'OpenClassrooms nous permet d'intégrer l'interface du site de Booki en utilisant du code HTML et CSS.",
    competences: [
      'Installer un environnement de développement front-end',
      'Implémenter une interface responsive avec HTML et CSS',
      'Intégrer du contenu conformément à une maquette avec HTML et CSS',
    ],
    tags: ['HTML', 'CSS', 'Responsive', 'Figma'],
    pictures: [
      '/assets/projects/booki/mock0.webp',
      '/assets/projects/booki/mock1.webp',
      '/assets/projects/booki/mock2.webp',
      '/assets/projects/booki/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Booki/',
    codeLink: 'https://github.com/Matthieu83600/Booki',
  },
  {
    id: 'project3',
    title: 'Ohmyfood',
    category: 'OpenClassrooms',
    description:
      "Le projet 4 du parcours Intégrateur Web d'OpenClassrooms consite à intégrer l'interface du site d'Ohmyfood en commençant par la version mobile.",
    competences: [
      'Intégrer une maquette en mobile-first',
      'Mettre en œuvre des animations CSS',
      'Versionner son projet avec Git et Github',
    ],
    tags: [
      'HTML',
      'Sass',
      'Responsive',
      'First Mobile',
      'Figma',
      'Git',
      'GitHub',
    ],
    pictures: [
      '/assets/projects/ohmyfood/mock0.webp',
      '/assets/projects/ohmyfood/mock1.webp',
      '/assets/projects/ohmyfood/mock2.webp',
      '/assets/projects/ohmyfood/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/OhMyFood/',
    codeLink: 'https://github.com/Matthieu83600/OhMyFood',
  },
  {
    id: 'project4',
    title: 'Print It',
    category: 'OpenClassrooms',
    description:
      "Le projet 5 du parcours Intégrateur Web d'OpenClassrooms nous permet de découvrir le langage JavaScript au travers du site de Print It.",
    competences: ['Programmer en utilisant les fondamentaux de JavaScript'],
    tags: ['HTML', 'CSS', 'JavaScript', 'VSCode'],
    pictures: [
      '/assets/projects/print-it/mock0.webp',
      '/assets/projects/print-it/mock1.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Print-It/',
    codeLink: 'https://github.com/Matthieu83600/Print-It',
  },
  {
    id: 'project5',
    title: 'Portfolio - Sophie Bluel',
    category: 'OpenClassrooms',
    description:
      "Le projet 6 du parcours Intégrateur Web d'OpenClassrooms nous emmène sur la conception du site portfolio d'une architecte en utilisant JavaScript et en communiquant avec une API.",
    infos:
      'Si vous souhaitez voir le projet, veuillez suivre le readme pour lancer le backend / frontend du projet.',
    competences: [
      'Gérer les événements utilisateurs avec JavaScript',
      'Manipuler les éléments du DOM avec JavaScript',
      'Récupérer les données utilisateurs dans le JavaScript via des formulaires',
    ],
    tags: ['HTML', 'CSS', 'JavaScript', 'Figma', 'API', 'Swagger'],
    pictures: [
      '/assets/projects/portfolio-sophie-bluel/mock0.webp',
      '/assets/projects/portfolio-sophie-bluel/mock1.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Portfolio-Sophie-Bluel',
  },
  {
    id: 'project6',
    title: 'Menu Maker',
    category: 'OpenClassrooms',
    description:
      "Le projet 7 du parcours Intégrateur Web d'OpenClassrooms est différent des autres projets réalisés, il s'agit de planifier le développement du prochain site de notre client Qwenta.",
    competences: [
      'Présenter la solution technique',
      "Rédiger les spécifications techniques d'un projet web à partir de besoins fonctionnels",
      'Découper une fonctionnalités en tâches pour préparer le développement',
      'Mettre en place une méthode de veille technologique',
      'Suivre le déroulement du projet grâce à un outil de gestion de projet',
    ],
    tags: [
      'Gestion de projet',
      'Kanban',
      'Méthode agile',
      'Veille technologique',
    ],
    pictures: [
      '/assets/projects/menu-maker/mock0.webp',
      '/assets/projects/menu-maker/mock1.webp',
      '/assets/projects/menu-maker/mock2.webp',
      '/assets/projects/menu-maker/mock3.webp',
      '/assets/projects/menu-maker/mock4.webp',
      '/assets/projects/menu-maker/mock5.webp',
      '/assets/projects/menu-maker/mock6.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Menu-Maker',
  },
  {
    id: 'project7',
    title: 'Kasa',
    category: 'OpenClassrooms',
    description:
      "Le projet 8 du parcours Intégrateur Web d'OpenClassrooms consiste à développer la nouvelle plateforme web de Kasa en utilisant React.",
    competences: [
      'Initialiser une application avec Create React App',
      "Configurer la navigation entre les pages de l'application avec React Router",
      "Développer des éléments de l'interface d'un site web grâce à des composants React",
      'Mettre en œuvre des animations CSS',
      'Développer une interface web avec Sass',
    ],
    tags: ['React', 'React-Router', 'Sass', 'Responsive', 'Figma', 'JSON'],
    pictures: [
      '/assets/projects/kasa/mock0.webp',
      '/assets/projects/kasa/mock1.webp',
      '/assets/projects/kasa/mock2.webp',
      '/assets/projects/kasa/mock3.webp',
    ],
    demoLink: 'https://kasa-matthieubonjour.vercel.app/',
    codeLink: 'https://github.com/Matthieu83600/Kasa',
  },
  {
    id: 'project8',
    title: 'Nina Carducci',
    category: 'OpenClassrooms',
    description:
      "Le projet 9 du parcours Intégrateur Web d'OpenClassrooms consiste à améliorer les performances et le référencement naturel du site d'un client.",
    competences: ["Optimiser la performance d'un site web"],
    tags: ['HTML', 'CSS', 'JavaScript', 'Responsive', 'SEO', 'LightHouse'],
    pictures: [
      '/assets/projects/nina-carducci/mock0.webp',
      '/assets/projects/nina-carducci/mock1.webp',
      '/assets/projects/nina-carducci/mock2.webp',
      '/assets/projects/nina-carducci/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Nina-Carducci/',
    codeLink: 'https://github.com/Matthieu83600/Nina-Carducci',
  },
  {
    id: 'project9',
    title: '724 events',
    category: 'OpenClassrooms',
    description:
      "Le projet 10 du parcours Intégrateur Web consiste à débugger le site d'une agence d'événementiel appelée 724events.",
    competences: [
      'Débugger un site web grâce aux Chrome DevTools',
      'Rédiger un cahier de recette pour tester un site',
    ],
    tags: [
      'React',
      'Tests unitaires',
      "Tests d'intégration",
      'Debug',
      'Chrome DevTools',
    ],
    pictures: [
      '/assets/projects/724events/mock0.webp',
      '/assets/projects/724events/mock1.webp',
    ],
    demoLink: 'https://724events-matthieubonjour.vercel.app/',
    codeLink: 'https://github.com/Matthieu83600/724events',
  },
  {
    id: 'project10',
    title: 'Argent Bank',
    category: 'OpenClassrooms',
    description:
      "Le projet 11 du parcours Intégrateur Web d'OpenClassrooms consiste à implémenter le front-end d'une application bancaire : Argent Bank en utilisant React.",
    infos:
      'Si vous souhaitez voir le projet, veuillez suivre le readme pour lancer le backend / frontend du projet.',
    competences: [
      "Afficher les données du back end sur l'interface via des appels API",
      'Configurer des routes API pour la communication client / serveur',
      'Implémenter la gestion des données avec Redux pour assurer le fonctionnement du front',
    ],
    tags: [
      'React',
      'React-Router',
      'Redux',
      'Sass',
      'API',
      'Swagger',
      'Responsive',
    ],
    pictures: [
      '/assets/projects/argent-bank/mock0.webp',
      '/assets/projects/argent-bank/mock1.webp',
      '/assets/projects/argent-bank/mock2.webp',
      '/assets/projects/argent-bank/mock3.webp',
      '/assets/projects/argent-bank/mock4.webp',
      '/assets/projects/argent-bank/mock5.webp',
      '/assets/projects/argent-bank/mock6.webp',
      '/assets/projects/argent-bank/mock7.webp',
      '/assets/projects/argent-bank/mock8.webp',
      '/assets/projects/argent-bank/mock9.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/ArgentBank-FrontEnd',
  },
  {
    id: 'project11',
    title: 'Mon Portfolio',
    category: 'OpenClassrooms',
    description:
      "Le projet 12 et dernier projet du parcours Intégrateur Web d'OpenClassrooms consiste à créer et mettre en ligne son site portfolio.",
    infos:
      'Vous pouvez retrouver le code de mon ancien portfolio créé lors de ma formation, vous êtes actuellement sur mon nouveau portfolio codé avec Nextjs.',
    competences: ['Déployer un site statique en ligne'],
    tags: [
      'React',
      'React-router',
      'Sass',
      'Styled-components',
      'React-responsive-carousel',
      'Emailjs',
      'Prettier',
      'JSON',
      'Figma',
    ],
    pictures: [
      '/assets/projects/my-portfolio/mock0.webp',
      '/assets/projects/my-portfolio/mock1.webp',
      '/assets/projects/my-portfolio/mock2.webp',
      '/assets/projects/my-portfolio/mock3.webp',
      '/assets/projects/my-portfolio/mock4.webp',
      '/assets/projects/my-portfolio/mock5.webp',
      '/assets/projects/my-portfolio/mock6.webp',
      '/assets/projects/my-portfolio/mock7.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Portfolio',
  },
  {
    id: 'project12',
    title: 'Watowatch',
    category: 'React',
    description:
      "Ce projet consiste à retourner toutes les séries depuis l'API externe de TMDB. Chaque jour, une nouvelle suggestion de séries TV à regarder.",
    infos: 'Ce site a été rédigé en anglais.',
    tags: ['React', 'Axios', 'TMDB-API', 'React-bootstrap-icons'],
    pictures: [
      '/assets/projects/watowatch/mock0.webp',
      '/assets/projects/watowatch/mock1.webp',
      '/assets/projects/watowatch/mock2.webp',
      '/assets/projects/watowatch/mock3.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Portfolio',
    demoLink: 'https://tv-show-adviser-two-mocha.vercel.app/',
  },
  {
    id: 'project13',
    title: 'ISpent',
    category: 'React',
    description:
      "Ce projet consiste à suivre vos dépenses. Simple et efficace, vous rentrez votre rentrée d'argent et vos dépenses. Utilise React-redux pour gérer le store et Redux-persist pour garder en mémoire vos données en localStorage.",
    infos: 'Ce site a été rédigé en anglais.',
    tags: ['React', 'React-Redux', 'Redux-persist'],
    pictures: [
      '/assets/projects/ispent/mock0.webp',
      '/assets/projects/ispent/mock1.webp',
      '/assets/projects/ispent/mock2.webp',
      '/assets/projects/ispent/mock3.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/React-expense-tracker',
    demoLink: 'https://react-expense-tracker-drab-rho.vercel.app/',
  },
  {
    id: 'project14',
    title: 'Florence',
    category: 'HTML',
    description:
      "Création d'une landing page basique pour m'exercer sur le langage HTML et le CSS.",
    tags: ['HTML', 'CSS'],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/Florence',
    demoLink: 'https://matthieu83600.github.io/Florence/',
  },
  {
    id: 'project15',
    title: "Rand'images",
    category: 'React',
    description: 'Mini-projet consistant à créer des custom hooks.',
    tags: ['React', 'Bootstrap', 'Axios', 'Custom hooks'],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/React-rand-images',
    demoLink: 'https://react-rand-images-six.vercel.app/',
  },
  {
    id: 'project16',
    title: 'Zest',
    category: 'JavaScript',
    description:
      "Mini-projet créé lors d'un processus de recrutement d'une entreprise. Zest est un mini réseau social basé sur un style neumorphisme et responsive.",
    infos: "Aucun back-end n'est utilisé pour ce projet.",
    tags: ['HTML', 'CSS', 'JavaScript', 'Fontawesome'],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/Zest',
    demoLink: 'https://matthieu83600.github.io/Zest/',
  },
  {
    id: 'project30',
    title: 'Mon Portfolio 2.0',
    category: 'Next',
    description:
      "Pour un meilleur référencement naturel, et une lecture plus facile des robots d'indexation, j'ai décidé de redévelopper mon portfolio avec Next.js. avec les conseils de mon évaluateur lors de mon dernier projet avec OpenClassrooms.",
    infos: 'Vous êtes actuellement en train de naviguer dessus 😊',
    competences: [
      'Concevoir un site avec Next.js',
      'Apprendre à utiliser Tailwind CSS',
    ],
    tags: ['Next', 'TypeScript', 'Tailwind CSS', 'Next-themes', 'React-icons'],
    pictures: [
      '/assets/projects/portfolio-v2/mock0.webp',
      '/assets/projects/portfolio-v2/mock1.webp',
      '/assets/projects/portfolio-v2/mock2.webp',
      '/assets/projects/portfolio-v2/mock3.webp',
    ],
    demoLink: 'https://matthieubonjour.dev/',
    codeLink: 'https://github.com/Matthieu83600/portfolio-nextjs',
  },
  {
    id: 'project31',
    title: 'Eternal Twin - DinoRPG',
    category: 'OpenSource',
    description:
      "J'ai rejoint un projet communautaire open source pour continuer à développer mes compétences, apprendre à travailler en équipe, et découvrir de nouveaux langages. J'essaye de contribuer autant sur la partie front que la partie back du projet.",
    tags: ['Vue', 'TypeScript', 'Nodejs', 'Express', 'API', 'Postgresql'],
    pictures: [
      '/assets/projects/eternal-twin/mock0.webp',
      '/assets/projects/eternal-twin/mock1.webp',
      '/assets/projects/eternal-twin/mock2.webp',
    ],
    codeLink: 'https://gitlab.com/eternaltwin/dinorpg/dinorpg',
    demoLink: 'https://dinorpg.eternaltwin.org/',
  },
];
