import { Project } from '@/types/projects.types';

export const PROJECTS: Project[] = [
  {
    id: 'project0',
    title: 'project0.title',
    category: 'Filter.OpenClassrooms',
    description: 'project0.description',
    competences: ['project0.competences.1'],
    tags: ['Tags.html', 'Tags.css', 'Tags.git'],
    pictures: [
      '/assets/projects/riding-cities/mock0.webp',
      '/assets/projects/riding-cities/mock1.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Riding-Cities/',
    codeLink: 'https://github.com/Matthieu83600/Riding-Cities',
  },
  {
    id: 'project1',
    title: 'project1.title',
    category: 'Filter.OpenClassrooms',
    description: 'project1.description',
    competences: [
      'project1.competences.1',
      'project1.competences.2',
      'project1.competences.3',
    ],
    tags: [
      'Tags.html',
      'Tags.css',
      'Tags.responsive',
      'Tags.figma',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/booki/mock0.webp',
      '/assets/projects/booki/mock1.webp',
      '/assets/projects/booki/mock2.webp',
      '/assets/projects/booki/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Booki/',
    codeLink: 'https://github.com/Matthieu83600/Booki',
  },
  {
    id: 'project2',
    title: 'project2.title',
    category: 'Filter.OpenClassrooms',
    description: 'project2.description',
    competences: [
      'project2.competences.1',
      'project2.competences.2',
      'project2.competences.3',
    ],
    tags: [
      'Tags.html',
      'Tags.sass',
      'Tags.mobileFirst-workflow',
      'Tags.responsive',
      'Tags.figma',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/ohmyfood/mock0.webp',
      '/assets/projects/ohmyfood/mock1.webp',
      '/assets/projects/ohmyfood/mock2.webp',
      '/assets/projects/ohmyfood/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/OhMyFood/',
    codeLink: 'https://github.com/Matthieu83600/OhMyFood',
  },
  {
    id: 'project3',
    title: 'project3.title',
    category: 'Filter.OpenClassrooms',
    description: 'project3.description',
    competences: ['project3.competences.1'],
    tags: ['Tags.html', 'Tags.css', 'Tags.js', 'Tags.git'],
    pictures: [
      '/assets/projects/print-it/mock0.webp',
      '/assets/projects/print-it/mock1.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Print-It/',
    codeLink: 'https://github.com/Matthieu83600/Print-It',
  },
  {
    id: 'project4',
    title: 'project4.title',
    category: 'Filter.OpenClassrooms',
    description: 'project4.description',
    infos: 'project4.infos',
    competences: [
      'project4.competences.1',
      'project4.competences.2',
      'project4.competences.3',
    ],
    tags: [
      'Tags.html',
      'Tags.css',
      'Tags.js',
      'Tags.figma',
      'Tags.api',
      'Tags.git',
      'Tags.postman',
    ],
    pictures: [
      '/assets/projects/portfolio-sophie-bluel/mock0.webp',
      '/assets/projects/portfolio-sophie-bluel/mock1.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Portfolio-Sophie-Bluel',
  },
  {
    id: 'project5',
    title: 'project5.title',
    category: 'Filter.OpenClassrooms',
    description: 'project5.description',
    competences: [
      'project5.competences.1',
      'project5.competences.2',
      'project5.competences.3',
      'project5.competences.4',
      'project5.competences.5',
    ],
    tags: ['Tags.project', 'Tags.kanban', 'Tags.agile', 'Tags.veille'],
    pictures: [
      '/assets/projects/menu-maker/mock0.webp',
      '/assets/projects/menu-maker/mock1.webp',
      '/assets/projects/menu-maker/mock2.webp',
      '/assets/projects/menu-maker/mock3.webp',
      '/assets/projects/menu-maker/mock4.webp',
      '/assets/projects/menu-maker/mock5.webp',
      '/assets/projects/menu-maker/mock6.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Menu-Maker',
  },
  {
    id: 'project6',
    title: 'project6.title',
    category: 'Filter.OpenClassrooms',
    description: 'project6.description',
    competences: [
      'project6.competences.1',
      'project6.competences.2',
      'project6.competences.3',
      'project6.competences.4',
      'project6.competences.5',
    ],
    tags: [
      'Tags.react',
      'Tags.react-router',
      'Tags.sass',
      'Tags.json',
      'Tags.responsive',
      'Tags.git',
      'Tags.figma',
    ],
    pictures: [
      '/assets/projects/kasa/mock0.webp',
      '/assets/projects/kasa/mock1.webp',
      '/assets/projects/kasa/mock2.webp',
      '/assets/projects/kasa/mock3.webp',
    ],
    demoLink: 'https://kasa-matthieubonjour.vercel.app/',
    codeLink: 'https://github.com/Matthieu83600/Kasa',
  },
  {
    id: 'project7',
    title: 'project7.title',
    category: 'Filter.OpenClassrooms',
    description: 'project7.description',
    competences: ['project7.competences.1'],
    tags: [
      'Tags.html',
      'Tags.css',
      'Tags.js',
      'Tags.responsive',
      'Tags.seo',
      'Tags.lighthouse',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/nina-carducci/mock0.webp',
      '/assets/projects/nina-carducci/mock1.webp',
      '/assets/projects/nina-carducci/mock2.webp',
      '/assets/projects/nina-carducci/mock3.webp',
    ],
    demoLink: 'https://matthieu83600.github.io/Nina-Carducci/',
    codeLink: 'https://github.com/Matthieu83600/Nina-Carducci',
  },
  {
    id: 'project8',
    title: 'project8.title',
    category: 'Filter.OpenClassrooms',
    description: 'project8.description',
    competences: ['project8.competences.1', 'project8.competences.2'],
    tags: [
      'Tags.react',
      'Tags.tu',
      'Tags.ti',
      'Tags.debug',
      'Tags.git',
      'Tags.chrome',
    ],
    pictures: [
      '/assets/projects/724events/mock0.webp',
      '/assets/projects/724events/mock1.webp',
    ],
    demoLink: 'https://724events-matthieubonjour.vercel.app/',
    codeLink: 'https://github.com/Matthieu83600/724events',
  },
  {
    id: 'project9',
    title: 'project9.title',
    category: 'Filter.OpenClassrooms',
    description: 'project9.description',
    infos: 'project9.infos',
    competences: [
      'project9.competences.1',
      'project9.competences.2',
      'project9.competences.3',
    ],
    tags: [
      'Tags.react',
      'Tags.react-router',
      'Tags.redux',
      'Tags.sass',
      'Tags.responsive',
      'Tags.api',
      'Tags.postman',
      'Tags.swagger',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/argent-bank/mock0.webp',
      '/assets/projects/argent-bank/mock1.webp',
      '/assets/projects/argent-bank/mock2.webp',
      '/assets/projects/argent-bank/mock3.webp',
      '/assets/projects/argent-bank/mock4.webp',
      '/assets/projects/argent-bank/mock5.webp',
      '/assets/projects/argent-bank/mock6.webp',
      '/assets/projects/argent-bank/mock7.webp',
      '/assets/projects/argent-bank/mock8.webp',
      '/assets/projects/argent-bank/mock9.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/ArgentBank-FrontEnd',
  },
  {
    id: 'project10',
    title: 'project10.title',
    category: 'Filter.OpenClassrooms',
    description: 'project10.description',
    infos: 'project10.infos',
    competences: ['project10.competences.1'],
    tags: [
      'Tags.react',
      'Tags.react-router',
      'Tags.sass',
      'Tags.styled-components',
      'Tags.react-responsive-carousel',
      'Tags.emailjs',
      'Tags.prettier',
      'Tags.json',
      'Tags.git',
      'Tags.figma',
    ],
    pictures: [
      '/assets/projects/my-portfolio/mock0.webp',
      '/assets/projects/my-portfolio/mock1.webp',
      '/assets/projects/my-portfolio/mock2.webp',
      '/assets/projects/my-portfolio/mock3.webp',
      '/assets/projects/my-portfolio/mock4.webp',
      '/assets/projects/my-portfolio/mock5.webp',
      '/assets/projects/my-portfolio/mock6.webp',
      '/assets/projects/my-portfolio/mock7.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/Portfolio',
  },
  {
    id: 'project11',
    title: 'project11.title',
    category: 'Filter.Udemy',
    description: 'project11.description',
    infos: 'project11.infos',
    competences: ['project11.competences.1', 'project11.competences.2'],
    tags: [
      'Tags.react',
      'Tags.css',
      'Tags.axios',
      'Tags.tmdb-api',
      'Tags.react-bootstrap-icons',
      'Tags.responsive',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/watowatch/mock0.webp',
      '/assets/projects/watowatch/mock1.webp',
      '/assets/projects/watowatch/mock2.webp',
      '/assets/projects/watowatch/mock3.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/TV-Show-Adviser',
    demoLink: 'https://tv-show-adviser-two-mocha.vercel.app/',
  },
  {
    id: 'project12',
    title: 'project12.title',
    category: 'Filter.Udemy',
    description: 'project12.description',
    infos: 'project12.infos',
    competences: ['project12.competences.1', 'project12.competences.2'],
    tags: [
      'Tags.react',
      'Tags.css',
      'Tags.redux',
      'Tags.redux-persist',
      'Tags.react-bootstrap-icons',
      'Tags.responsive',
      'Tags.git',
    ],
    pictures: [
      '/assets/projects/ispent/mock0.webp',
      '/assets/projects/ispent/mock1.webp',
      '/assets/projects/ispent/mock2.webp',
      '/assets/projects/ispent/mock3.webp',
    ],
    codeLink: 'https://github.com/Matthieu83600/React-expense-tracker',
    demoLink: 'https://react-expense-tracker-drab-rho.vercel.app/',
  },
  {
    id: 'project13',
    title: 'project13.title',
    category: 'Filter.Udemy',
    description: 'project13.description',
    competences: ['project13.competences.1'],
    tags: ['Tags.html', 'Tags.css', 'Tags.git'],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/Florence',
    demoLink: 'https://matthieu83600.github.io/Florence/',
  },
  {
    id: 'project14',
    title: 'project14.title',
    category: 'Filter.Udemy',
    description: 'project14.description',
    competences: [
      'project14.competences.1',
      'project14.competences.2',
      'project14.competences.3',
      'project14.competences.4',
      'project14.competences.5',
    ],
    tags: [
      'Tags.react',
      'Tags.bootstrap',
      'Tags.axios',
      'Tags.hooks',
      'Tags.git',
    ],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/React-rand-images',
    demoLink: 'https://react-rand-images-six.vercel.app/',
  },
  {
    id: 'project15',
    title: 'project15.title',
    category: 'Filter.otherProjects',
    description: 'project15.description',
    infos: 'project15.infos',
    competences: [
      'project15.competences.1',
      'project15.competences.2',
      'project15.competences.3',
      'project15.competences.4',
    ],
    tags: [
      'Tags.html',
      'Tags.css',
      'Tags.neumorphism',
      'Tags.js',
      'Tags.responsive',
      'Tags.git',
    ],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/Zest',
    demoLink: 'https://matthieu83600.github.io/Zest/',
  },
  {
    id: 'project16',
    title: 'project16.title',
    category: 'Filter.udemy',
    description: 'project16.description',
    competences: [
      'project16.competences.1',
      'project16.competences.2',
      'project16.competences.3',
      'project16.competences.4',
      'project16.competences.5',
    ],
    tags: [
      'Tags.html',
      'Tags.css',
      'Tags.js',
      'Tags.bootstrap',
      'Tags.responsive',
      'Tags.git',
    ],
    pictures: [],
    codeLink: 'https://github.com/Matthieu83600/Agence-Lorem',
    demoLink: 'https://matthieu83600.github.io/Agence-Lorem/',
  },
  {
    id: 'project30',
    title: 'project30.title',
    category: 'Filter.otherProjects',
    description: 'project30.description',
    infos: 'project30.infos',
    competences: [
      'project30.competences.1',
      'project30.competences.2',
      'project30.competences.3',
    ],
    tags: [
      'Tags.nextjs',
      'Tags.typescript',
      'Tags.tailwind',
      'Tags.nextjs-themes',
      'Tags.nextjs-intl',
    ],
    pictures: [
      '/assets/projects/portfolio-v2/mock0.webp',
      '/assets/projects/portfolio-v2/mock1.webp',
      '/assets/projects/portfolio-v2/mock2.webp',
      '/assets/projects/portfolio-v2/mock3.webp',
    ],
    demoLink: 'https://matthieubonjour.dev/',
    codeLink: 'https://github.com/Matthieu83600/portfolio-nextjs',
  },
  {
    id: 'project31',
    title: 'project31.title',
    category: 'Filter.OpenSource',
    description: 'project31.description',
    tags: [
      'project31.tags.1',
      'Tags.typescript',
      'Tags.sass',
      'project31.tags.4',
      'project31.tags.5',
      'project31.tags.6',
      'project31.tags.7',
      'project31.tags.8',
      'project31.tags.9',
    ],
    pictures: [
      '/assets/projects/eternal-twin/mock0.webp',
      '/assets/projects/eternal-twin/mock1.webp',
      '/assets/projects/eternal-twin/mock2.webp',
    ],
    codeLink: 'https://gitlab.com/eternaltwin/dinorpg/dinorpg',
    demoLink: 'https://dinorpg.eternaltwin.org/',
  },
];
